export const TOKEN_AUTH = "token-auth";
export const REFRESH_TOKEN_AUTH = "refreshToken-auth";

export const CALCULATOR_CART = "calculator-cart";

export const CALCULATOR_STEP = {
  STRUCTURES_SCREEN: "STRUCTURES_SCREEN",
  LIST_STRUCTURES_ADDED_SCREEN: "LIST_STRUCTURES_ADDED_SCREEN",
  SELECT_PRODUCT_SCREEN: "SELECT_PRODUCT_SCREEN",
  DIMENSIONS_SCREEN: "DIMENSIONS_SCREEN",
  LIST_TOTAL_PRODUCTS_SCREEN: "LIST_TOTAL_PRODUCTS_SCREEN",
  END_SCREEN: "END_SCREEN",
};

export const CALCULATOR_ACTIONS = {
  ADD_STRUCTURE: "ADD_STRUCTURE",
  SELECT_COLOR: "SELECT_COLOR",
  SELECT_MASILLA: "SELECT_MASILLA",
  SET_DIMENSIONS: "SET_DIMENSIONS",
  SELECT_CINTA: "SELECT_CINTA",
  LIST_STRUCTURES: "LIST_STRUCTURES",
  ADD_PRODUCT: "ADD_PRODUCT",
  ADD_MULTIPLE_PRODUCT: "ADD_MULTIPLE_PRODUCT",
  SELECT_WIDTH: "SELECT_WIDTH",
  SELECT_DEEP: "SELECT_DEEP",
  SELECT_MOLDURA: "SELECT_MOLDURA",
};

// ENDPOINTS API GO

export const BASE_URL = `http://localhost:4321`;
export const API_ENDPOINT = `https://api.vallejosmateriales.com.ar`;
// export const API_ENDPOINT = `http://127.0.0.1:5002`;

export const API_VERSION = `${API_ENDPOINT}/api/v1`;

export const PRODUCTS_BY_CODE_API = `${API_VERSION}/cart/products`;
export const GET_QUANTITIES_API = `${API_VERSION}/calculator/get-quantities`;

export const CALCULATOR_API = `${API_VERSION}/calculator`;
export const GET_ACCESORIES_API = `${CALCULATOR_API}/accesories`;
export const GET_PVC_API = `${CALCULATOR_API}/pvc`;
