import type { IProductDetailResponse } from "../types/IProducDetail";

export const mapProductDetail = (product: any): IProductDetailResponse => {
  return {
    id: product.id,
    brandDetail: product.brandDetail,
    name: product.name,
    price: product.price,
    code: product.code,
    descriptionTwo: product.descriptionTwo,
    images: product.images,
    descriptionThree: product.descriptionThree,
    descriptionFour: product.descriptionFour,
    discount: product.discount,
    EAN: product.EAN,
    DUN: product.DUN,
    model: product.model,
    presentation: product?.presentation || "",
    mainImage: product.mainImage,
    detailImages: product.detailImages,
    priceDifference: product.priceDifference,
    priceDifferenceWithIva: product.priceDifferenceWithIva,
    priceDifferenceWithIvaAndDiscount:
      product.priceDifferenceWithIvaAndDiscount,
    priceWithIva: product.priceWithIva,
    priceWithIvaAndDiscount: product.priceWithIvaAndDiscount,
    stackable: product.stackable,
    lineDetail: product.lineDetail,
    slug: product.slug,
    status: product.status,
    priority: product.priority,
    relatedProducts: product.relatedProducts,
    stock: product.stock,
    video: product.video || "",
    video2: product.video2 || "",
    pdfDocument: product.pdfDocument || "",
    pdfDocument2: product.pdfDocument2 || "",
    pdfDocumentTitle: product.pdfDocumentTitle || "",
    pdfDocumentTitle2: product.pdfDocumentTitle2 || "",
    detailText1: product.detailText1 || "",
    detailText2: product.detailText2 || "",
    detailText3: product.detailText3 || "",
    useMode: product.useMode || "",
    performance: product.performance || "",
    weight: product.weight,
    benefitPercentDiscount: product.benefitPercentDiscount,
  };
};
